
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Badmus
 */
public class Input_Details extends javax.swing.JFrame {
ArrayList<Trip> list;
    /**
     * Creates new form Input_Details
     */
    public Input_Details() {
        initComponents();
        ArrayList<Trip> list= new ArrayList<>();
        Show_Users_In_JTable();
    }

    
   public Connection getConnection()
   {
       Connection con;

       try {
           con = DriverManager.getConnection("jdbc:mysql://localhost/test_db", "root","");
           return con;
       } 
      catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }
   public ArrayList<Insert> getInsertList()
   {
       ArrayList<Insert> InsertList = new ArrayList<Insert>();
       Connection connection = getConnection();
       
       String query = "SELECT * FROM  `users` ";
       Statement st;
       ResultSet rs;
       
       try {
           st = connection.createStatement();
           rs = st.executeQuery(query);

           Insert insert;

           while(rs.next())
           {
        insert = new Insert(rs.getString("Pickup"),rs.getString("Destination"),rs.getString("ID"),rs.getString("Passenger"),rs.getString("Amount"),rs.getString("Acc"),rs.getString("Tel"));
               InsertList.add(insert);
           }

       } 
      catch (Exception e) {
           e.printStackTrace();
       }
       return InsertList;
   }  
   
   //DisplayData in Table
   
   public void Show_Users_In_JTable()
   {
       DefaultTableModel model = (DefaultTableModel)jTable_Display.getModel();
               model.setRowCount(0);
               
               java.util.Date date = new java.util.Date();
        
            SimpleDateFormat Date = new SimpleDateFormat("yyyy-MM-dd");
            String dateOfTrip = Date.format(date);
    
    list = new SQL().getTrips("WHERE date= '"+dateOfTrip+"'");
       
       Object[] row = new Object[8];
       for (int i = 0; i < list.size(); i++ )
       {
           row[0] = list.get(i).getTime();
           row[1] = list.get(i).getPickup();
           row[2] = list.get(i).getDestination();
           row[3] = list.get(i).getDriver_id();
           row[4] = list.get(i).getPassenger_name();
           row[5] = list.get(i).getAmount();
           row[6] = list.get(i).getAccount();
           row[7] = list.get(i).getTelephone();
           
           model.addRow(row);
       }
   }
    
// Execute The Insert Update And Delete Querys
   public void executeSQlQuery(String query, String message)
   {
       Connection con = getConnection();
       Statement st;
       try{
           st = con.createStatement();
           if((st.executeUpdate(query)) == 1)
           {
               // refresh jtable data
               DefaultTableModel model = (DefaultTableModel)jTable_Display.getModel();
               model.setRowCount(0);
               Show_Users_In_JTable();
               
               JOptionPane.showMessageDialog(null, "Data "+message+" Succefully");
           }else{
               JOptionPane.showMessageDialog(null, "Data Not "+message);
           }
       }catch(Exception ex){
           ex.printStackTrace();
       }
   }
   
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Time = new javax.swing.JTextField();
        jTextField_Pickup = new javax.swing.JTextField();
        jTextField_Destination = new javax.swing.JTextField();
        jTextField_ID = new javax.swing.JTextField();
        jTextField_P = new javax.swing.JTextField();
        jTextField_Amount = new javax.swing.JTextField();
        jTextField_Acc = new javax.swing.JTextField();
        jTextField_Tel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display = new javax.swing.JTable();
        jButton_Insert = new javax.swing.JButton();
        jButton_Edit = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_RegDispatcher = new javax.swing.JMenuItem();
        jMenuItem_RegisterDriver = new javax.swing.JMenuItem();
        jMenuItem_ViewReport = new javax.swing.JMenuItem();
        jMenuItem_Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Time:");

        jLabel2.setText("PickUp:");

        jLabel3.setText("Destination:");

        jLabel4.setText("Driver ID:");

        jLabel5.setText("Passenger :");

        jLabel6.setText("Amount:");

        jLabel7.setText("Account:");

        jLabel8.setText("Telephone:");

        jTextField_Time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TimeActionPerformed(evt);
            }
        });

        jTable_Display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Time", "Pickup", "Destination", "Driver ID", "Passenger", "Amount", "Account", "Telephone"
            }
        ));
        jTable_Display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DisplayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display);

        jButton_Insert.setText("Insert");
        jButton_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InsertActionPerformed(evt);
            }
        });

        jButton_Edit.setText("Update");
        jButton_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditActionPerformed(evt);
            }
        });

        jButton_Delete.setText("Delete");
        jButton_Delete.setToolTipText("");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jButton1.setText("Go to Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem_RegDispatcher.setText("Register Dispatcher");
        jMenuItem_RegDispatcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_RegDispatcherActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_RegDispatcher);

        jMenuItem_RegisterDriver.setText("Register Driver");
        jMenuItem_RegisterDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_RegisterDriverActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_RegisterDriver);

        jMenuItem_ViewReport.setText("Report");
        jMenuItem_ViewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ViewReportActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_ViewReport);

        jMenuItem_Exit.setText("Exit");
        jMenuItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Acc, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_P, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Destination, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Pickup, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton_Insert)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_Edit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton_Delete)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_Pickup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_Destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_Acc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Insert)
                            .addComponent(jButton_Edit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Delete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_TimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TimeActionPerformed

    String selected_trip_id;
    private void jTable_DisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DisplayMouseClicked
        // TODO add your handling code here:
         // Get The Index Of The Slected Row 
       
             int i = jTable_Display.getSelectedRow();
        
             if(i<0){
                 return;
             }
        
             selected_trip_id=list.get(i).getTrip_id();
             
        TableModel model = jTable_Display.getModel();
        
        jTextField_Time.setText(model.getValueAt(i,0).toString());

        jTextField_Pickup.setText(model.getValueAt(i,1).toString());

        jTextField_Destination.setText(model.getValueAt(i,2).toString());

        jTextField_ID.setText(model.getValueAt(i,3).toString());
        
        jTextField_P.setText(model.getValueAt(i,4).toString());

        jTextField_Amount.setText(model.getValueAt(i,5).toString());

        jTextField_Acc.setText(model.getValueAt(i,6).toString());
        
        jTextField_Tel.setText(model.getValueAt(i,7).toString());
                                        
    }//GEN-LAST:event_jTable_DisplayMouseClicked

    private void jButton_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InsertActionPerformed
        // TODO add your handling code here:
        String  time, pickup, destination, driver_id, passenger_name, amount, account, telephone,date;
        time=jTextField_Time.getText();
        pickup=jTextField_Pickup.getText();
        destination=jTextField_Destination.getText();
        driver_id=jTextField_ID.getText();
        passenger_name=jTextField_P.getText();
        amount=jTextField_Amount.getText();
        account=jTextField_Acc.getText();
        telephone=jTextField_Tel.getText();
        
        Trip trip= new Trip(time, pickup, destination, driver_id, passenger_name, amount, account, telephone, null);
        SQL sql= new SQL();
        boolean response=sql.addTrip(trip);
        if(response){
            JOptionPane.showMessageDialog(rootPane, "Saved");
            Show_Users_In_JTable();
        }else{
                        JOptionPane.showMessageDialog(rootPane, "Not Saved");

        }
    }//GEN-LAST:event_jButton_InsertActionPerformed

    private void jButton_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditActionPerformed
        // TODO add your handling code here:
          if(selected_trip_id.isEmpty() || selected_trip_id==null){
            return;
        }
          
         
          String  time, pickup, destination, driver_id, passenger_name, amount, account, telephone,date;
        time=jTextField_Time.getText();
        pickup=jTextField_Pickup.getText();
        destination=jTextField_Destination.getText();
        driver_id=jTextField_ID.getText();
        passenger_name=jTextField_P.getText();
        amount=jTextField_Amount.getText();
        account=jTextField_Acc.getText();
        telephone=jTextField_Tel.getText();
        
        Trip trip= new Trip(selected_trip_id,time, pickup, destination, driver_id, passenger_name, amount, account, telephone, null);
        SQL sql= new SQL();
        boolean response=sql.updateTrip(trip);
        
            JOptionPane.showMessageDialog(rootPane, "Update success!");
            Show_Users_In_JTable();
        
        
    }//GEN-LAST:event_jButton_EditActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        // TODO add your handling code here:
        
        if(selected_trip_id.isEmpty() || selected_trip_id==null){
            return;
        }
        
        SQL sql= new SQL();
        sql.deleteTrip(selected_trip_id);
        JOptionPane.showMessageDialog(rootPane, "Delete success");
        Show_Users_In_JTable();
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jMenuItem_RegDispatcherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_RegDispatcherActionPerformed
        // TODO add your handling code here:
        new RegisterDispatcher().setVisible(true);
    }//GEN-LAST:event_jMenuItem_RegDispatcherActionPerformed

    private void jMenuItem_RegisterDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_RegisterDriverActionPerformed
        // TODO add your handling code here:
        new RegisterDriver().setVisible(true);
    }//GEN-LAST:event_jMenuItem_RegisterDriverActionPerformed

    private void jMenuItem_ViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ViewReportActionPerformed
        // TODO add your handling code here:
        new ReportForm().setVisible(true);
    }//GEN-LAST:event_jMenuItem_ViewReportActionPerformed

    private void jMenuItem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_ExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new  ReportForm().setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Edit;
    private javax.swing.JButton jButton_Insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_Exit;
    private javax.swing.JMenuItem jMenuItem_RegDispatcher;
    private javax.swing.JMenuItem jMenuItem_RegisterDriver;
    private javax.swing.JMenuItem jMenuItem_ViewReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display;
    private javax.swing.JTextField jTextField_Acc;
    private javax.swing.JTextField jTextField_Amount;
    private javax.swing.JTextField jTextField_Destination;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_P;
    private javax.swing.JTextField jTextField_Pickup;
    private javax.swing.JTextField jTextField_Tel;
    private javax.swing.JTextField jTextField_Time;
    // End of variables declaration//GEN-END:variables
}
